import type { Metadata } from "next";
import { Geist, Geist_Mono, Varela_Round } from "next/font/google";
import "./globals.css";
import ThemeContext from "@/context/Theme";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const varelaRound = Varela_Round({
  variable: "--font-varela",
  subsets: ['latin'],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${varelaRound.variable} antialiased bg-base-300 text-base-content`}
      >
        <ThemeContext>
          <Navbar />
          <div className="flex flex-col h-[calc(100vh-86px)]">
            {children}
          </div>
        </ThemeContext>
      </body>
    </html>
  );
}
