import type { Metadata } from "next";
import { Gabarito, Varela_Round } from "next/font/google";
import "./globals.css";
import ThemeContext from "@/context/Theme";
import { ToasterClient } from "@/components/ToasterClient";
import Auth from "@/context/Auth";
import Data from "@/context/Data";


const varelaRound = Varela_Round({
  variable: "--font-varela",
  subsets: ['latin'],
  weight: "400"
});


const gabarito = Gabarito({
  variable: "--font-gabarito",
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${varelaRound.variable} ${gabarito.variable} antialiased bg-base-300 text-base-content`}
        suppressHydrationWarning={true}
      >
        <ThemeContext>
          <Auth>
            <Data>
              <div className="flex flex-col h-[calc(100vh-86px)]">
                {children}
              </div>
              <ToasterClient />
            </Data>
          </Auth>
        </ThemeContext>
      </body>
    </html>
  );
}
